
ALTER TABLE cg_symbols ADD COLUMN IF NOT EXISTS arity_json VARCHAR;
ALTER TABLE cg_symbols ADD COLUMN IF NOT EXISTS visibility VARCHAR;
ALTER TABLE cg_symbols ADD COLUMN IF NOT EXISTS kwargs_json VARCHAR;
ALTER TABLE cg_symbols ADD COLUMN IF NOT EXISTS accepts_block BOOLEAN;
