-- Drop the page_rank index that makes replacePageRanks fatal (bd tea-rags-mcp-snbzk).
--
-- `replacePageRanks` rewrites the whole table each finalize:
--   DELETE FROM cg_symbols_metrics; INSERT ...   (one transaction)
-- On DuckDB 1.5.3 that DELETE aborts against the ART index over the DOUBLE
-- page_rank column:
--   Invalid Input Error: Failed to delete all rows from index.
--                        Only deleted 0 out of 714 rows.
-- The error is FATAL — it invalidates the database handle for the rest of the
-- process, so everything the run had still to write (cg_run_stats among them)
-- is lost and the whole index run exits non-zero. Observed live on the tea-rags
-- self-index 2026-08-11.
--
-- The index buys nothing: page_rank is never a predicate or a sort key. The two
-- readers are `SELECT symbol_id, page_rank FROM cg_symbols_metrics` (full scan,
-- method-edge-reader.ts) and `... WHERE symbol_id = ?` (graph-analytics-store.ts),
-- which the PRIMARY KEY on symbol_id already serves.
DROP INDEX IF EXISTS idx_cg_symbols_metrics_page_rank;
