coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        informational: false
    patch:
      default:
        target: 90%
        threshold: 1%
        informational: false

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false
