#!/usr/bin/env python3
"""Generate `python/vocabulary/stdlib-modules.ts` (bd tea-rags-mcp-mmckn).

The UNION of `sys.stdlib_module_names` across the interpreters the corpora run
on, because the vocabulary is one snapshot serving all five: netbox is 3.12,
polar is 3.14, httpx claims 3.9. A union over-approximates by a handful of
modules removed between versions, and over-approximating the STDLIB is the safe
direction — the alternative is calling a stdlib receiver a project miss.

Run it explicitly when the version list changes; the output is committed, and
nothing in the build regenerates it.

    uv run --no-project --python 3.13 python scripts/py-oracle/gen-stdlib-modules.py \\
        > src/core/domains/language/python/vocabulary/stdlib-modules.ts
"""

from __future__ import annotations

import json
import subprocess
import sys

VERSIONS = ["3.10", "3.11", "3.12", "3.13", "3.14"]


def names_for(version: str) -> set[str]:
    out = subprocess.run(
        ["uv", "run", "--no-project", "--python", version, "python", "-c",
         "import sys, json; print(json.dumps(sorted(sys.stdlib_module_names)))"],
        capture_output=True, text=True, check=True,
    )
    return set(json.loads(out.stdout))


def main() -> int:
    union: set[str] = set()
    for version in VERSIONS:
        union |= names_for(version)
    union = {name for name in union if not name.startswith("_")}

    body = ",\n  ".join(f'"{name}"' for name in sorted(union))
    sys.stdout.write(
        "/**\n"
        f" * Top-level stdlib module names — the union over CPython {VERSIONS[0]}-{VERSIONS[-1]}.\n"
        " *\n"
        " * GENERATED by `scripts/py-oracle/gen-stdlib-modules.py`. Do not edit by hand;\n"
        " * re-run the generator when the version list in its header changes.\n"
        " *\n"
        " * A frozen module-level Set: the vocabulary is consulted once per unresolved\n"
        " * call on every corpus, so this must be a hash lookup and never a scan, and it\n"
        " * must never touch the filesystem.\n"
        " */\n"
        "export const PYTHON_STDLIB_MODULES: ReadonlySet<string> = new Set([\n"
        f"  {body},\n"
        "]);\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
