import type { CodegraphTier, LanguageCapability, TypingTieredCodegraph } from "../../../contracts/types/language.js";
import { UNSUPPORTED_FALLBACK } from "./fallback.js";

/** Display order + human label for the matrix (NOT the supported()/Map order). */
const DISPLAY: readonly (readonly [string, string])[] = [
  ["typescript", "TypeScript"],
  ["javascript", "JavaScript"],
  ["python", "Python"],
  ["go", "Go"],
  ["java", "Java"],
  ["rust", "Rust"],
  ["ruby", "Ruby"],
  ["bash", "Bash"],
  ["markdown", "Markdown"],
];

function isTypingTiered(tier: CodegraphTier | TypingTieredCodegraph): tier is TypingTieredCodegraph {
  return typeof tier === "object";
}

function codegraphCell(tier: CodegraphTier | TypingTieredCodegraph): string {
  if (isTypingTiered(tier)) {
    const rbs = tier["rbs/sorbet"] === "tbd" ? "TBD" : tier["rbs/sorbet"];
    return `untyped **${tier.untyped}** · YARD **${tier.yard}** · RBS/Sorbet **${rbs}**`;
  }
  return `**${tier}**`;
}

function testsCell(tests: LanguageCapability["tests"]): string {
  const tierLabel = tests.tier === "na" ? "N/A" : tests.tier;
  const label = tests.tech === "—" ? tests.detection : tests.tech;
  return `**${tierLabel}** · ${label}`;
}

function matrixRow(cap: LanguageCapability, name: string): string {
  return `| **${name}** | **${cap.ast.tier}** · ${cap.ast.engine} | ${testsCell(cap.tests)} | ${codegraphCell(cap.codegraph.tier)} |`;
}

function fallbackRow(): string {
  const langs = UNSUPPORTED_FALLBACK.map((f) => f.language).join(" / ");
  return `| **${langs}** | **none** · CharacterChunker | **none** | **none** |`;
}

function getOrThrow(caps: Map<string, LanguageCapability>, key: string): LanguageCapability {
  const cap = caps.get(key);
  if (!cap) throw new Error(`renderRule: missing capability descriptor for "${key}"`);
  return cap;
}

/**
 * Render the agent-facing `language-compatibility.md` rule from the capability
 * Map. Static product fact only — the measured `resolveSuccessRate` is never
 * baked in (it is per-index state owned by prime).
 */
export function renderRule(caps: Map<string, LanguageCapability>): string {
  const rows = DISPLAY.map(([key, name]) => matrixRow(getOrThrow(caps, key), name)).join("\n");
  const forHumans = DISPLAY.map(([key, name]) => `- **${name}** — ${getOrThrow(caps, key).codegraph.tech}`).join("\n");

  return `# Language Compatibility

<!-- GENERATED by \`npm run gen:lang-compat\` from src/core/domains/language/<lang>/capability.ts — DO NOT EDIT. -->

How much to trust tea-rags data **per language**. Every column answers one
question the agent must settle before acting on a result:

- **AST chunking** — is a chunk the source of truth (a whole symbol), so
  \`find_symbol\` suffices and no \`Read\` is needed?
- **Tests chunking** — is a test chunk a coherent unit (scope / case preserved)?
- **Codegraph** — can call-graph signals (\`get_callers\` / \`get_callees\` /
  \`trace_path\` / \`fanIn\` / \`pageRank\`) be trusted for this language?

**Source of truth** is each \`src/core/domains/language/<lang>/capability.ts\`
descriptor, aggregated by \`LanguageFactory.capabilities()\`. This file is
GENERATED — edit the descriptor and run \`npm run gen:lang-compat\`, never edit
here. Per-project realized numbers live in **prime**, never in this file.

## Matrix

| Language | AST code chunking | Tests code chunking | Codegraph capability |
| --- | --- | --- | --- |
${rows}
${fallbackRow()}

## Scales — what each tier means for the agent

**AST code chunking** — can you trust the chunk as a complete symbol?

- **full** — tree-sitter cuts on real symbol boundaries. The chunk /
  \`find_symbol\` result IS the source of truth; gather code from it, do NOT
  \`Read\` to "see the real code". \`Read\` only to MODIFY. (An oversized symbol is
  hard-cap split into \`#partN\` chunks — one part is NOT the whole symbol;
  \`find_symbol(symbolId)\` reassembles every part into one trusted result. See
  \`search-cascade.md\` → After-Search Navigation.)
- **partial** — chunked by section / heading (Markdown). A section is coherent
  for docs; there are no code symbols to split.
- **none** — CharacterChunker splits at arbitrary offsets; a chunk may cut a
  symbol in half. Here \`Read\` is a legitimate fallback to obtain exact code.

**Tests code chunking** — can you trust a test chunk as a unit?

- **high** — test scope (describe / context / it) preserved as a chunk
  (incl. injected setup for Ruby).
- **medium** — only function / method boundaries; nesting and setup context lost.
- **low** — test framework unrecognized; chunked as plain functions.
- **N/A** — doc-only.

**Codegraph** — can you trust call-graph signals?

- Order: **maximum** > **high** > **moderate** > **minimal** > **none**.
- **maximum** — full typed resolution; edges near-complete (YARD-annotated Ruby).
- **high** — reliable resolution (typed TS / JS; untyped Ruby's richest chain).
- **moderate** — structural resolution; dynamic-dispatch edges partial — treat
  \`fanIn\` / callers as a LOWER BOUND, not exhaustive.
- **minimal** — function extraction only, no dispatch.
- **none** — no call graph; codegraph signals absent.

## Realized trust = prime, not this table

This table is the **capability ceiling** of the mechanism — a static product
fact. The trust you actually get on YOUR index is prime's \`resolveSuccessRate\`
per language (it depends on the corpus). Variance is largest for dynamically
typed languages: Ruby is **high** untyped, **maximum** YARD-annotated, and drops
on un-annotated Rails — and that swing is a prime number, not a language
property.

**Consequence:** when prime reports a low \`resolveSuccessRate\`, an empty
\`get_callers\` is a resolution artifact, NOT "the symbol has no callers". Do not
conclude absence from a graph the index says is incomplete.

## For humans — resolution tech (not agent-actionable)

${forHumans}
`;
}
