import { describe, it, expect } from "vitest";

import { classify } from "../../../../src/core/infra/file-classification/index.js";

describe("classify", () => {
  it("flags Rails schema as generated", () => {
    const c = classify("db/schema.rb");
    expect(c.isGenerated).toBe(true);
    expect(c.isSource).toBe(false);
  });

  it("flags vendored code and protobufs as generated", () => {
    expect(classify("vendor/bundle/gems/x.rb").isGenerated).toBe(true);
    expect(classify("api/user.pb.go").isGenerated).toBe(true);
    expect(classify("proto/user_pb2.py").isGenerated).toBe(true);
  });

  it("does NOT flag ordinary source as generated", () => {
    const c = classify("app/models/user.rb");
    expect(c.isGenerated).toBe(false);
    expect(c.isSource).toBe(true);
  });

  it("flags test files via test patterns", () => {
    expect(classify("spec/models/user_spec.rb").isTest).toBe(true);
    expect(classify("src/foo.test.ts").isTest).toBe(true);
    expect(classify("app/models/user.rb").isTest).toBe(false);
  });

  it("detects content-marker generated files", () => {
    const c = classify("api/zz_generated.go", { contentHead: "// Code generated by protoc. DO NOT EDIT." });
    expect(c.isGenerated).toBe(true);
  });

  it("passes documentation flag through and excludes it from isSource", () => {
    const c = classify("README.md", { isDocumentation: true });
    expect(c.isDocumentation).toBe(true);
    expect(c.isSource).toBe(false);
    expect(c.isGenerated).toBe(false);
  });
});
