import { describe, expect, it } from "vitest";

import { classify } from "../../../../src/core/infra/file-classification/index.js";

describe("classify", () => {
  it("flags Rails schema as generated", () => {
    const c = classify("db/schema.rb");
    expect(c.isGenerated).toBe(true);
    expect(c.isSource).toBe(false);
  });

  it("flags vendored code and protobufs as generated", () => {
    expect(classify("vendor/bundle/gems/x.rb").isGenerated).toBe(true);
    expect(classify("api/user.pb.go").isGenerated).toBe(true);
    expect(classify("proto/user_pb2.py").isGenerated).toBe(true);
  });

  it("does NOT flag ordinary source as generated", () => {
    const c = classify("app/models/user.rb");
    expect(c.isGenerated).toBe(false);
    expect(c.isSource).toBe(true);
  });

  it("flags test files via test patterns", () => {
    expect(classify("spec/models/user_spec.rb").isTest).toBe(true);
    expect(classify("src/foo.test.ts").isTest).toBe(true);
    expect(classify("app/models/user.rb").isTest).toBe(false);
  });

  // G3a boundary: non-`*_spec.rb` files that still live under `spec/`
  // (support helpers, gem monkey-patches, mailer previews) MUST classify as
  // test so the codegraph exclusion filter keeps them out of the graph. A
  // `spec/support/gem_extensions/capybara.rb` reopening `module Capybara`
  // otherwise makes the gem constant look in-project and defeats the external
  // dispatch gate (dnd_helpers `Capybara…perform` cg_ambiguous_fanout noise).
  it("classifies spec/ support and mailer-preview boundary paths as test", () => {
    expect(classify("spec/support/x.rb").isTest).toBe(true);
    expect(classify("spec/support/dnd_helpers.rb").isTest).toBe(true);
    expect(classify("spec/support/gem_extensions/capybara.rb").isTest).toBe(true);
    expect(classify("spec/mailers/previews/y.rb").isTest).toBe(true);
    expect(classify("spec/mailers/previews/user_mailer_preview.rb").isTest).toBe(true);
  });

  it("does NOT classify production app code as test", () => {
    expect(classify("app/services/z.rb").isTest).toBe(false);
    expect(classify("app/models/user.rb").isTest).toBe(false);
    expect(classify("lib/tasks/import.rb").isTest).toBe(false);
  });

  it("detects content-marker generated files", () => {
    const c = classify("api/zz_generated.go", { contentHead: "// Code generated by protoc. DO NOT EDIT." });
    expect(c.isGenerated).toBe(true);
  });

  it("passes documentation flag through and excludes it from isSource", () => {
    const c = classify("README.md", { isDocumentation: true });
    expect(c.isDocumentation).toBe(true);
    expect(c.isSource).toBe(false);
    expect(c.isGenerated).toBe(false);
  });

  describe("PascalCase test suffixes match case-sensitively (bd tea-rags-mcp-ezm9o)", () => {
    it("does NOT flag a production file whose name merely ends in lowercase `test` / `it`", () => {
      expect(classify("src/main/java/com/acme/Latest.java").isTest).toBe(false);
      expect(classify("src/main/kotlin/com/acme/Contest.kt").isTest).toBe(false);
      expect(classify("src/main/java/com/acme/Audit.java").isTest).toBe(false);
      expect(classify("Sources/Billing/Latest.swift").isTest).toBe(false);
      expect(classify("src/Billing/Contests.cs").isTest).toBe(false);
      expect(classify("src/main/scala/Respec.scala").isTest).toBe(false);
      expect(classify("src/Latest.php").isTest).toBe(false);
    });

    it("still flags the PascalCase test conventions", () => {
      expect(classify("src/main/java/com/acme/LatestTest.java").isTest).toBe(true);
      expect(classify("src/main/java/com/acme/LatestTests.java").isTest).toBe(true);
      expect(classify("src/main/java/com/acme/LatestIT.java").isTest).toBe(true);
      expect(classify("src/main/kotlin/com/acme/ContestTest.kt").isTest).toBe(true);
      expect(classify("Sources/Billing/ContestTests.swift").isTest).toBe(true);
      expect(classify("src/Billing/ContestTests.cs").isTest).toBe(true);
      expect(classify("src/main/scala/ContestSpec.scala").isTest).toBe(true);
      expect(classify("src/ContestTest.php").isTest).toBe(true);
    });

    it("keeps directory conventions case-insensitive", () => {
      expect(classify("Tests/BillingTests/Latest.swift").isTest).toBe(true);
      expect(classify("Test/Contest.kt").isTest).toBe(true);
      expect(classify("Spec/Latest.java").isTest).toBe(true);
    });

    it("keeps lowercase conventions behaving as before", () => {
      expect(classify("pkg/repo_test.go").isTest).toBe(true);
      expect(classify("pkg/test_user.py").isTest).toBe(true);
      expect(classify("src/app.spec.ts").isTest).toBe(true);
      expect(classify("src/App.Spec.ts").isTest).toBe(true);
      expect(classify("lib/user_spec.rb").isTest).toBe(true);
    });

    it("keeps C / C++ suffixes case-insensitive — their convention is mixed-case (`foo_test.cc`)", () => {
      expect(classify("src/parser_test.cc").isTest).toBe(true);
      expect(classify("src/parser_tests.cpp").isTest).toBe(true);
      expect(classify("src/ParserTest.cpp").isTest).toBe(true);
      expect(classify("src/unittest.c").isTest).toBe(true);
    });
  });
});
