import { describe, it, expect } from "vitest";

import { classify } from "../../../../src/core/infra/file-classification/index.js";

describe("classify", () => {
  it("flags Rails schema as generated", () => {
    const c = classify("db/schema.rb");
    expect(c.isGenerated).toBe(true);
    expect(c.isSource).toBe(false);
  });

  it("flags vendored code and protobufs as generated", () => {
    expect(classify("vendor/bundle/gems/x.rb").isGenerated).toBe(true);
    expect(classify("api/user.pb.go").isGenerated).toBe(true);
    expect(classify("proto/user_pb2.py").isGenerated).toBe(true);
  });

  it("does NOT flag ordinary source as generated", () => {
    const c = classify("app/models/user.rb");
    expect(c.isGenerated).toBe(false);
    expect(c.isSource).toBe(true);
  });

  it("flags test files via test patterns", () => {
    expect(classify("spec/models/user_spec.rb").isTest).toBe(true);
    expect(classify("src/foo.test.ts").isTest).toBe(true);
    expect(classify("app/models/user.rb").isTest).toBe(false);
  });

  // G3a boundary: non-`*_spec.rb` files that still live under `spec/`
  // (support helpers, gem monkey-patches, mailer previews) MUST classify as
  // test so codegraph does not extract them under CODEGRAPH_EXCLUDE_TESTS. A
  // `spec/support/gem_extensions/capybara.rb` reopening `module Capybara`
  // otherwise makes the gem constant look in-project and defeats the external
  // dispatch gate (dnd_helpers `Capybara…perform` cg_ambiguous_fanout noise).
  it("classifies spec/ support and mailer-preview boundary paths as test", () => {
    expect(classify("spec/support/x.rb").isTest).toBe(true);
    expect(classify("spec/support/dnd_helpers.rb").isTest).toBe(true);
    expect(classify("spec/support/gem_extensions/capybara.rb").isTest).toBe(true);
    expect(classify("spec/mailers/previews/y.rb").isTest).toBe(true);
    expect(classify("spec/mailers/previews/user_mailer_preview.rb").isTest).toBe(true);
  });

  it("does NOT classify production app code as test", () => {
    expect(classify("app/services/z.rb").isTest).toBe(false);
    expect(classify("app/models/user.rb").isTest).toBe(false);
    expect(classify("lib/tasks/import.rb").isTest).toBe(false);
  });

  it("detects content-marker generated files", () => {
    const c = classify("api/zz_generated.go", { contentHead: "// Code generated by protoc. DO NOT EDIT." });
    expect(c.isGenerated).toBe(true);
  });

  it("passes documentation flag through and excludes it from isSource", () => {
    const c = classify("README.md", { isDocumentation: true });
    expect(c.isDocumentation).toBe(true);
    expect(c.isSource).toBe(false);
    expect(c.isGenerated).toBe(false);
  });
});
