/**
 * Single source of truth for "what kind of file is this" path patterns.
 * Consolidates the previously codegraph-only generated/test pattern lists
 * (was trajectory/codegraph/exclusion.ts) so git enrichment, codegraph, and
 * any future consumer share one definition. `ignore` (gitignore) syntax.
 */

/** Machine-generated files — never meaningfully owned, often huge. */
export const GENERATED_PATTERNS: readonly string[] = [
  // Rails generated AR schema — re-authored by `rails db:migrate`.
  "**/db/schema.rb",
  // Vendored third-party code (bundled gems, asset libs).
  "**/vendor/**",
  // Protobuf / gRPC generated stubs.
  "*.pb.go",
  "*_pb2.py",
  // Common "generated" naming conventions.
  "*.generated.*",
  "*.g.dart",
];

/**
 * Test DIRECTORY conventions no single language owns: a `spec/` dir is shared
 * by Ruby and JavaScript, a `test/` dir is universal. Matched case-insensitively
 * (SwiftPM's `Tests/`). The per-language FILE shapes (`*_test.go`,
 * `*Test.java`) are not here: each language declares its own in
 * `domains/language/<lang>/test-files.ts`, and they reach the classifier by
 * injection — see `./test-file-conventions.ts` (bd tea-rags-mcp-vjz6s).
 */
export const COMMON_TEST_DIRECTORY_PATTERNS: readonly string[] = [
  "**/tests/**",
  "**/test/**",
  "**/__tests__/**",
  "**/spec/**",
];

/**
 * Development tooling that lives beside the product: scripts (`script/` is the
 * Rails spelling), spikes, benchmarks, examples and fixtures, at any depth
 * (bd tea-rags-mcp-r8hme.9). Source code — indexed, chunked, searchable, in the
 * codegraph — but not part of the architecture a boundary diagnostic judges:
 * a spike deep-importing a worker pool is not a leaking abstraction, and a
 * report script importing the detector does not stabilise it. `bin/` is left
 * out on purpose — it holds the shipped entry points of a CLI package.
 * `.gitignore` syntax: a trailing `/` names a directory at any depth.
 */
export const NON_PRODUCTION_PATTERNS: readonly string[] = [
  "scripts/",
  "script/",
  "spikes/",
  "benchmarks/",
  "bench/",
  "examples/",
  "fixtures/",
  "__fixtures__/",
];

/** First-N-lines markers that identify generated files with non-standard names. */
export const GENERATED_CONTENT_MARKERS: readonly RegExp[] = [
  /Code generated .* DO NOT EDIT/i,
  /@generated\b/,
  /^\s*#\s*Autogenerated/im,
];

/**
 * User-supplied extra generated patterns via `TEA_RAGS_GENERATED_PATTERNS`
 * (comma-separated gitignore globs). Shared knob — affects both git-skip and
 * codegraph graph-exclusion. The legacy `CODEGRAPH_CUSTOM_EXCLUDE` env keeps
 * working independently in codegraph's own filter.
 */
export const USER_GENERATED_PATTERNS: readonly string[] = (process.env.TEA_RAGS_GENERATED_PATTERNS ?? "")
  .split(",")
  .map((s) => s.trim())
  .filter(Boolean);
