/**
 * Single source of truth for "what kind of file is this" path patterns.
 * Consolidates the previously codegraph-only generated/test pattern lists
 * (was trajectory/codegraph/exclusion.ts) so git enrichment, codegraph, and
 * any future consumer share one definition. `ignore` (gitignore) syntax.
 */

/** Machine-generated files — never meaningfully owned, often huge. */
export const GENERATED_PATTERNS: readonly string[] = [
  // Rails generated AR schema — re-authored by `rails db:migrate`.
  "**/db/schema.rb",
  // Vendored third-party code (bundled gems, asset libs).
  "**/vendor/**",
  // Protobuf / gRPC generated stubs.
  "*.pb.go",
  "*_pb2.py",
  // Common "generated" naming conventions.
  "*.generated.*",
  "*.g.dart",
];

/** Conventional test-file shapes for every language with a codegraph walker. */
export const TEST_PATTERNS: readonly string[] = [
  "**/tests/**",
  "**/test/**",
  "**/__tests__/**",
  "**/spec/**",
  "**/*.test.js",
  "**/*.test.jsx",
  "**/*.test.ts",
  "**/*.test.tsx",
  "**/*.test.mjs",
  "**/*.test.cjs",
  "**/*.spec.js",
  "**/*.spec.jsx",
  "**/*.spec.ts",
  "**/*.spec.tsx",
  "**/*.spec.mjs",
  "**/*.spec.cjs",
  "**/test_*.py",
  "**/*_test.py",
  "**/conftest.py",
  "**/*_test.rb",
  "**/*_spec.rb",
  "**/*Test.java",
  "**/*Tests.java",
  "**/*IT.java",
  "**/*_test.go",
  "**/*_test.rs",
];

/** First-N-lines markers that identify generated files with non-standard names. */
export const GENERATED_CONTENT_MARKERS: readonly RegExp[] = [
  /Code generated .* DO NOT EDIT/i,
  /@generated\b/,
  /^\s*#\s*Autogenerated/im,
];

/**
 * User-supplied extra generated patterns via `TEA_RAGS_GENERATED_PATTERNS`
 * (comma-separated gitignore globs). Shared knob — affects both git-skip and
 * codegraph graph-exclusion. The legacy `CODEGRAPH_CUSTOM_EXCLUDE` env keeps
 * working independently in codegraph's own filter.
 */
export const USER_GENERATED_PATTERNS: readonly string[] = (process.env.TEA_RAGS_GENERATED_PATTERNS ?? "")
  .split(",")
  .map((s) => s.trim())
  .filter(Boolean);
